### ISSUE TITLE
fails to install

### ISSUE THREAD

**Issue by hemna** [kvndrsslr/sketchybar-app-font#127]
Copying and pasting the install instructions leads to failure.

```
╭─sketchybar-app-font on  main is 📦 v2.0.17 via  v22.9.0 ❯
└─> pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +413
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 413, reused 0, downloaded 413, added 413, done
node_modules/.pnpm/ttf2woff2@5.0.0/node_modules/ttf2woff2: Running install script, done in 6.6s

dependencies:
+ chokidar 3.5.3
+ express 4.18.2
+ livereload 0.9.3

devDependencies:
+ svgtofont 4.1.1

Done in 11.8s
╭─sketchybar-app-font on  main [!] is 📦 v2.0.17 via  v22.9.0 took 11s ❯
└─> pnpm run build:install

> sketchybar-app-font@2.0.17 build:install /Users/I530566/tmp/sketchybar-app-font
> node ./install.js

(node:33127) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Found a line element in the icon ":maps:" the result could be different than expected.
Found a line element in the icon ":maps:" the result could be different than expected.
Found a clipPath element in the icon ":tana:" the result may be different than expected.
Found a clipPath element in the icon ":tana:" the result may be different than expected.
Found a clipPath element in the icon ":tana:" the result may be different than expected.
Font created
SUCCESS SVG font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.svg
SUCCESS TTF font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.ttf
SUCCESS EOT font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.eot
SUCCESS WOFF font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.woff
SUCCESS WOFF2 font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.woff2
SUCCESS Svg Symbol font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.symbol.svg
SUCCESS Created /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.json
SUCCESS Created React Components.
done!
╭─sketchybar-app-font on  main [!] is 📦 v2.0.17 via  v22.9.0 took 2s ❯
└─> pnpm run build:install -- $HOME/.config/sketchybar/scripts/my-script.sh

> sketchybar-app-font@2.0.17 build:install /Users/I530566/tmp/sketchybar-app-font
> node ./install.js "--" "/Users/I530566/.config/sketchybar/scripts/my-script.sh"

(node:34902) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Found a line element in the icon ":maps:" the result could be different than expected.
Found a line element in the icon ":maps:" the result could be different than expected.
Found a clipPath element in the icon ":tana:" the result may be different than expected.
Found a clipPath element in the icon ":tana:" the result may be different than expected.
Found a clipPath element in the icon ":tana:" the result may be different than expected.
Font created
SUCCESS SVG font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.svg
SUCCESS TTF font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.ttf
SUCCESS EOT font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.eot
SUCCESS WOFF font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.woff
SUCCESS WOFF2 font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.woff2
SUCCESS Svg Symbol font successfully created!
  ╰┈▶ /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.symbol.svg
SUCCESS Created /Users/I530566/tmp/sketchybar-app-font/dist/sketchybar-app-font.json
SUCCESS Created React Components.
done!
node:fs:441
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/Users/I530566/tmp/sketchybar-app-font/--'
    at Object.readFileSync (node:fs:441:20)
    at install (file:///Users/I530566/tmp/sketchybar-app-font/install.js:17:31)
    at file:///Users/I530566/tmp/sketchybar-app-font/install.js:46:3
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:483:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/I530566/tmp/sketchybar-app-font/--'
}

Node.js v22.9.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by kvndrsslr** [comment]
It seems that the `--` are not necessary anymore with your version of `pnpm`:

```
Error: ENOENT: no such file or directory, open '/Users/I530566/tmp/sketchybar-app-font/--'
```

You would also have to specify which script to install into (it's likely not `my-script.sh` ;)).
